export const STORAGE_KEYS = {
    SECURITY_TYPE_TERM_MAPPER: 'SECURITY_TYPE_TERM_MAPPER',
    SECURITY_MAPPER: 'SECURITY_MAPPER',
    LAST_UPDATED_AT: 'LAST_UPDATED_AT',
    OLD_DATA_PAGE_NUM: 'OLD_DATA_PAGE_NUM'
}

export const ONE_DAY_OFFSET = 1000 * 60 * 60 * 24

export const FETCH_PAGE_SIZE = 500

export const DEFAULT_RECENT_FETCH_DAYS = 365 // 1 year
